name: 'Code Coverage Output'
description: 'Calculate the Code Coverage in GH Actions'
branding:
  icon: check-square
  color: green
inputs:
  path:
    description: 'lcov path'
    required: false
    default: './coverage/lcov.info'
  exclude:
    description: 'list of files you would like to exclude from coverage'
    required: false
outputs:
  code_coverage: 
    description: 'The code coverage from 0 to 100'
runs:
  using: 'node16'
  main: 'dist/index.js'
